/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import static Gui.studentEnrolment.subjectMap;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.intellijthemes.FlatGruvboxDarkSoftIJTheme;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.mysql;

/**
 *
 * @author dilmi
 */
public class classRegestor extends javax.swing.JFrame {

    public static HashMap<String,Integer> teacherMap = new HashMap();
    public static  HashMap<String,Integer> subjectMap = new HashMap();
    /**
     * Creates new form classRegestor
     */
    public classRegestor() {
        initComponents();
        loadTeachers();
        loadsubject();
        loadClass();
    }
    
    private void loadTeachers(){
    try{
        ResultSet teachersResult = mysql.execute("SELECT * FROM `teacher`");
        Vector teacher = new Vector();
        teacher.add("Select teacher");
        
        while(teachersResult.next()){
        teacher.add(teachersResult.getString("First_Name"));
        teacherMap.put(teachersResult.getString("First_Name"),teachersResult.getInt("Tno"));
        }
        DefaultComboBoxModel teachermodel = new  DefaultComboBoxModel(teacher);
              jComboBox2.setModel(teachermodel);
         }catch(Exception e){
            e.printStackTrace();
        }
    
    }
     private void loadsubject(){
    
         try{
            ResultSet subjectResult = mysql.execute("SELECT * FROM `subject`");
            
            Vector subject = new Vector();
            subject.add("Select Subject");
            
            while(subjectResult.next()){
             subject.add(subjectResult.getString("Subject_name"));
             subjectMap.put(subjectResult.getString("Subject_name"),subjectResult.getInt("Subno"));
            }
             DefaultComboBoxModel subjectmodel = new  DefaultComboBoxModel(subject);
              jComboBox1.setModel(subjectmodel);
          }catch(Exception e){
            e.printStackTrace();
        }
    }
     private void loadClass(){
      try{
          ResultSet classresult = mysql.execute("SELECT * FROM `class` INNER JOIN `teacher` ON `class`.`Teacher_Tno`=`teacher`.`Tno`"
          +"INNER JOIN`subject`ON `class`.`Subject_Subno`=`subject`.`Subno`");
          
          DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            
            while(classresult.next()){
            
                 Vector<String> Class = new Vector();
                 
                 Class.add(classresult.getString("ClassNo"));
                 Class.add(classresult.getString("Class_name"));
                 Class.add(classresult.getString("First_Name"));
                 Class.add(classresult.getString("Subject_name"));
                 Class.add(classresult.getString("TimeSlot"));
                 
                       model.addRow(Class);
                  jTable1.setModel(model);
                        
                
            }
           }catch(Exception e){
            e.printStackTrace();
      }
     
     }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("ROG Fonts", 3, 24)); // NOI18N
        jLabel1.setText("Class Regestor");

        jButton2.setFont(new java.awt.Font("ROG Fonts", 3, 18)); // NOI18N
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Class Name");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Class Number");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Teacher");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Time Slot");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject" }));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Select Subject");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Teacher" }));

        jButton4.setFont(new java.awt.Font("ROG Fonts", 1, 14)); // NOI18N
        jButton4.setText("Regester Class");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("ROG Fonts", 1, 14)); // NOI18N
        jButton5.setText("Update Class Details");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Class NUmber", "Class name", "Teacher", "Subject", "Time Slot"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(384, 384, 384))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            String ClassNumber = jTextField2.getText();
            String ClassName = jTextField3.getText();
            String Timeslot= jTextField4.getText();
            
            DateFormat formatter = new SimpleDateFormat("hh:mm:ss");
            Date timeSlot = (Date)formatter.parse(Timeslot);
            
            
            String Teacher = String.valueOf(jComboBox2.getSelectedItem());
            String Subject = String.valueOf(jComboBox1.getSelectedItem());
            
            if(ClassNumber.isEmpty()){
                JOptionPane.showMessageDialog(this, "Enter Class Number",
                        "WARNING", JOptionPane.WARNING_MESSAGE);
            }else if(ClassName.isEmpty()){
                JOptionPane.showMessageDialog(this, "Enter Class Name",
                        "WARNING", JOptionPane.WARNING_MESSAGE);
            }else if(Timeslot.isEmpty()){
                JOptionPane.showMessageDialog(this, "Enter time Slot",
                        "WARNING", JOptionPane.WARNING_MESSAGE);
                
            }else if(Teacher.equals("Select teacher")){
                JOptionPane.showMessageDialog(this, "Select Teacher",
                        "WARNING", JOptionPane.WARNING_MESSAGE);
            }else if(Subject.equals("Select Subject")){
                JOptionPane.showMessageDialog(this, "Select Subject",
                        "WARNING", JOptionPane.WARNING_MESSAGE);
            }else{
                try{
                   // ResultSet classResult = mysql.execute("SELECT * FROM `class`"
                           // + "`ClassNo`='"+ClassNumber+"'AND `Class_name`='"+ClassName+"'AND `TimeSlot`='"+formatter.format(timeSlot)+"' AND `Teacher_Tno`='"+teacherMap.get(Teacher)+"'AND "
                          //  +"`Subject_Subno`='"+subjectMap.get(Subject)+"'");
                   // if(classResult.next()){
                       // JOptionPane.showMessageDialog(this, "This Class already exsite","Warning",JOptionPane.WARNING_MESSAGE);
                   // }else{
                        mysql.execute("INSERT INTO"
                                +"`class`(`ClassNo`,`Class_name`,`TimeSlot`,`Teacher_Tno`,`Subject_Subno`)"
                                +"VALUES ('"+ClassNumber+"','"+ClassName+"','"+formatter.format(timeSlot)+"','"+teacherMap.get(Teacher)+"','"+subjectMap.get(Subject)+"')");
                        
                        JOptionPane.showMessageDialog(this, "Class Regester SuccessFull",
                                "information", JOptionPane.INFORMATION_MESSAGE);
                   // }
                    
                }catch(Exception e){
                    e.printStackTrace();
                }
            }} catch (ParseException ex) {
            Logger.getLogger(classRegestor.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        home home = new home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      FlatDarkLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new classRegestor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
