/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import static Gui.studentEnrolment.cityMap;
import static Gui.studentEnrolment.subjectMap;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.intellijthemes.FlatGruvboxDarkSoftIJTheme;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.ButtonModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.mysql;

/**
 *
 * @author dilmi
 */
public class teacherEnrolment extends javax.swing.JFrame {
    
    public static HashMap<String,Integer> cityMap = new HashMap();
    public static  HashMap<String,Integer> subjectMap = new HashMap();
    /**
     * Creates new form teacher_enrolment
     */
    public teacherEnrolment() {
        initComponents();
        loadsubject();
        loadcity();
        loadTeachers();
    }
    
   private void loadcity(){
    
        try{
     ResultSet cityResult = mysql.execute("SELECT * FROM `city` ");
     
     Vector city = new Vector();
     city.add("Select City");
     
     while(cityResult.next()){
         city.add(cityResult.getString("city_name"));
       cityMap.put(cityResult.getString("city_name"),cityResult.getInt("city_id"));
     }
    DefaultComboBoxModel citymodel = new  DefaultComboBoxModel(city);
    jComboBox1.setModel(citymodel);
    
     }catch(Exception e){
            e.printStackTrace();
        }
    }
     
  private void loadsubject(){
    
         try{
            ResultSet subjectResult = mysql.execute("SELECT * FROM `subject`");
            
            Vector subject = new Vector();
            subject.add("Select Subject");
            
            while(subjectResult.next()){
             subject.add(subjectResult.getString("Subject_name"));
             subjectMap.put(subjectResult.getString("Subject_name"),subjectResult.getInt("Subno"));
            }
             DefaultComboBoxModel subjectmodel = new  DefaultComboBoxModel(subject);
              jComboBox2.setModel(subjectmodel);
          }catch(Exception e){
            e.printStackTrace();
        }
    }
  private void loadTeachers(){
      try{
   ResultSet teacherResult = mysql.execute("SELECT * FROM `teacher` INNER JOIN `gender` ON `teacher`.`Gender_gender_id`=`gender`.`gender_id`"
   +"INNER JOIN `subject` ON `teacher`.`Subject_Subno`=`subject`.`Subno`"
   +"INNER JOIN `teachers_address` ON `teacher`.`teachers_address_id`=`teachers_address`.`id`");
   
       DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            
            while(teacherResult.next()){
                
            Vector teacher = new Vector();
            
         teacher.add(teacherResult.getString("Tno"));
         teacher.add(teacherResult.getString("First_Name"));
         teacher.add(teacherResult.getString("Last_Name"));
         teacher.add(teacherResult.getString("Address_line1"));
         teacher.add(teacherResult.getString("Mobile"));
         teacher.add(teacherResult.getString("gender"));
         teacher.add(teacherResult.getString("Subject_name"));
               
                        model.addRow(teacher);
                  jTable1.setModel(model);
            }
    }catch(Exception e){
            e.printStackTrace();
        }
      
  }
  private void reset (){

  jTextField2.setText("");
  jTextField5.setText("");
  jTextField7.setText("");
  jTextField6.setText("");
  jTextField4.setText("");
  buttonGroup1.clearSelection();
  jComboBox1.setSelectedIndex(0);
  jComboBox2.setSelectedIndex(0);
  
  
  
  
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("ROG Fonts", 3, 24)); // NOI18N
        jLabel1.setText("Teacher Enrolment");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Teacher First Name");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Adress LIne 1");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Teacher Last Name");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Mobile Number");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Select Gender");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jRadioButton1.setText("Male");
        jRadioButton1.setActionCommand("1");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jRadioButton2.setText("Female");
        jRadioButton2.setActionCommand("2");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Select City");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject" }));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Addres Line 2");

        jButton3.setFont(new java.awt.Font("ROG Fonts", 0, 18)); // NOI18N
        jButton3.setText("Teacher Regester");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("ROG Fonts", 0, 18)); // NOI18N
        jButton4.setText("Teacher Details Update");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Teacher Number", "First Name", "Last Name", "Adress", "Mobile", "Gender", "Subject"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Select Subject");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject" }));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/3643764_back_backward_left_reply_turn_icon.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("search");

        jButton6.setFont(new java.awt.Font("ROG Fonts", 1, 18)); // NOI18N
        jButton6.setText("Home");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(231, 231, 231)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jRadioButton1)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioButton2))))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(485, 485, 485))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String TeacherFirstName = jTextField2.getText();
        String TeacherLastName = jTextField5.getText();
        String AddressLine1 = jTextField7.getText();
        String AddressLine2 = jTextField6.getText();
        String Mobile = jTextField4.getText();
        ButtonModel genderSelection = buttonGroup1.getSelection();
        String City = String.valueOf(jComboBox1.getSelectedItem());
         String Subject = String.valueOf(jComboBox2.getSelectedItem());
        
        if(TeacherFirstName.isEmpty()){
       JOptionPane.showMessageDialog(this, "Enter Teacher First Name",
                               "WARNING", JOptionPane.WARNING_MESSAGE);
        }else if (TeacherLastName.isEmpty()){
           JOptionPane.showMessageDialog(this, "Enter Teacher Last Name",
                               "WARNING", JOptionPane.WARNING_MESSAGE);
        }else if(AddressLine1.isEmpty()){
          JOptionPane.showMessageDialog(this, "Enter Address Lihne 1",
                               "WARNING", JOptionPane.WARNING_MESSAGE);
        }else if(AddressLine2.isEmpty()){
        JOptionPane.showMessageDialog(this, "Enter Address Lihne 2",
                               "WARNING", JOptionPane.WARNING_MESSAGE);
        }else if (Mobile.isEmpty()){
        JOptionPane.showMessageDialog(this, "Enter Mobile",
                               "WARNING", JOptionPane.WARNING_MESSAGE);
        }else if(genderSelection == null){
                JOptionPane.showMessageDialog(this, "Select Gender",
                               "WARNING", JOptionPane.WARNING_MESSAGE);
        }else if (Subject.equals("Select Subject")){
         JOptionPane.showMessageDialog(this, "Select Subject",
                               "WARNING", JOptionPane.WARNING_MESSAGE);
         }else if (Subject.equals("Select City")){
         JOptionPane.showMessageDialog(this, "Select City",
                               "WARNING", JOptionPane.WARNING_MESSAGE);
        }else{
        try{
            ResultSet teacherDetails = mysql.execute("SELECT * FROM `teacher`"
            +"WHERE  `First_Name`='"+TeacherFirstName+"' AND `Last_Name`='"+TeacherLastName+"'AND `Mobile`='"+Mobile+"' AND`status` = '1'");
            if(teacherDetails.next()){
               JOptionPane.showMessageDialog(this, "This Teacher already exsite","Warning",JOptionPane.WARNING_MESSAGE);
            }else{
            mysql.execute("INSERT INTO"
            +"`teachers_address`(`Address_line1`,`Address_line2`,`city_city_id`)"
            +"VALUES('"+AddressLine1+"','"+AddressLine2+"','"+cityMap.get(City)+"')");
            }
            ResultSet teacherAddress = mysql.execute("SELECT * FROM `teachers_address`"
            +"WHERE `Address_line1`='"+AddressLine1+"'AND `Address_line2`='"+AddressLine2+"'AND `city_city_id`='"+cityMap.get(City)+"'");
            teacherAddress.next();
            
            mysql.execute("INSERT INTO"
            +"`teacher` (`First_Name`,`Last_Name`,`Mobile`,`Gender_gender_id`,`teachers_address_id`,`Subject_Subno`,`status`)"
            +"VALUES ('"+TeacherFirstName+"','"+TeacherLastName+"','"+Mobile+"','"+genderSelection.getActionCommand()+"','"+teacherAddress.getString("id")+"','"+subjectMap.get(Subject)+"','1')");
            
            
            JOptionPane.showMessageDialog(this, "Teacher Regester SuccessFull",
                               "information", JOptionPane.INFORMATION_MESSAGE);
            
            reset();
            loadTeachers();
            
             }catch(Exception e){
            e.printStackTrace();
        }
        }
         
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    home home = new home();
    home.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        home home = new home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
    try{
         ResultSet searchDetails = mysql.execute("SELECT * FROM``teacher` INNER JOIN `address` ON `teacher`.`teachers_address`=`address`.`adress_id`"
         +"INNER JOIN `subject` ON `teacher`.`Subject_Subno`=`subject`.`Subno`"
         +"INNER JOIN `class` ON `teacher`.`Class_ClassNo`=`classs`.`ClassNo`"
         +"INNER JOIN `gender` ON `teacher`.`Gender_gender_id`=`gender`.`gender_id`");
         
         while(searchDetails.next()){
         
         }
          }catch(Exception e){
            e.printStackTrace();
    }
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
  FlatDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacherEnrolment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
